[package]
name = "plumbing"
version = "0.1.0"
authors = ["Guilherme Prearo <guiprearo@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = "1.4.0"

[dev-dependencies]
chrono = "0.4.15"
rand = "0.7.3"